packages:
  - "framework/*"
  - "developer/*"
  - "extensions/*"
  - "examples/*"
  - "artifact"
allowBuilds:
  '@biomejs/biome': true
  '@kungfu-tech/libnode': true
  core-js: true
  esbuild: true
  nx: true
  vue-demi: true
