// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ORDER_KUNGFU_LONGFIST_FB_H_
#define FLATBUFFERS_GENERATED_ORDER_KUNGFU_LONGFIST_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace kungfu {
namespace longfist {
namespace fb {

struct Order;
struct OrderBuilder;

enum class OrderStatus : int8_t {
  Unknown = 0,
  Submitted = 1,
  Pending = 2,
  Cancelled = 3,
  Error = 4,
  Filled = 5,
  PartialFilledNotActive = 6,
  PartialFilledActive = 7,
  Lost = 8,
  Cancelling = 9,
  Pause = 10,
  PendingSettlement = 11,
  MIN = Unknown,
  MAX = PendingSettlement
};

inline const OrderStatus (&EnumValuesOrderStatus())[12] {
  static const OrderStatus values[] = {
    OrderStatus::Unknown,
    OrderStatus::Submitted,
    OrderStatus::Pending,
    OrderStatus::Cancelled,
    OrderStatus::Error,
    OrderStatus::Filled,
    OrderStatus::PartialFilledNotActive,
    OrderStatus::PartialFilledActive,
    OrderStatus::Lost,
    OrderStatus::Cancelling,
    OrderStatus::Pause,
    OrderStatus::PendingSettlement
  };
  return values;
}

inline const char * const *EnumNamesOrderStatus() {
  static const char * const names[13] = {
    "Unknown",
    "Submitted",
    "Pending",
    "Cancelled",
    "Error",
    "Filled",
    "PartialFilledNotActive",
    "PartialFilledActive",
    "Lost",
    "Cancelling",
    "Pause",
    "PendingSettlement",
    nullptr
  };
  return names;
}

inline const char *EnumNameOrderStatus(OrderStatus e) {
  if (::flatbuffers::IsOutRange(e, OrderStatus::Unknown, OrderStatus::PendingSettlement)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOrderStatus()[index];
}

struct Order FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OrderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORDER_ID = 4,
    VT_RESTORE_TIME = 6,
    VT_STATUS = 8,
    VT_INSTRUMENT_ID = 10,
    VT_LIMIT_PRICE = 12,
    VT_VOLUME = 14,
    VT_VOLUME_LEFT = 16
  };
  uint64_t order_id() const {
    return GetField<uint64_t>(VT_ORDER_ID, 0);
  }
  bool mutate_order_id(uint64_t _order_id = 0) {
    return SetField<uint64_t>(VT_ORDER_ID, _order_id, 0);
  }
  int64_t restore_time() const {
    return GetField<int64_t>(VT_RESTORE_TIME, 0);
  }
  bool mutate_restore_time(int64_t _restore_time = 0) {
    return SetField<int64_t>(VT_RESTORE_TIME, _restore_time, 0);
  }
  kungfu::longfist::fb::OrderStatus status() const {
    return static_cast<kungfu::longfist::fb::OrderStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  bool mutate_status(kungfu::longfist::fb::OrderStatus _status = static_cast<kungfu::longfist::fb::OrderStatus>(0)) {
    return SetField<int8_t>(VT_STATUS, static_cast<int8_t>(_status), 0);
  }
  const ::flatbuffers::String *instrument_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INSTRUMENT_ID);
  }
  ::flatbuffers::String *mutable_instrument_id() {
    return GetPointer<::flatbuffers::String *>(VT_INSTRUMENT_ID);
  }
  double limit_price() const {
    return GetField<double>(VT_LIMIT_PRICE, 0.0);
  }
  bool mutate_limit_price(double _limit_price = 0.0) {
    return SetField<double>(VT_LIMIT_PRICE, _limit_price, 0.0);
  }
  double volume() const {
    return GetField<double>(VT_VOLUME, 0.0);
  }
  bool mutate_volume(double _volume = 0.0) {
    return SetField<double>(VT_VOLUME, _volume, 0.0);
  }
  double volume_left() const {
    return GetField<double>(VT_VOLUME_LEFT, 0.0);
  }
  bool mutate_volume_left(double _volume_left = 0.0) {
    return SetField<double>(VT_VOLUME_LEFT, _volume_left, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ORDER_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_RESTORE_TIME, 8) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyOffset(verifier, VT_INSTRUMENT_ID) &&
           verifier.VerifyString(instrument_id()) &&
           VerifyField<double>(verifier, VT_LIMIT_PRICE, 8) &&
           VerifyField<double>(verifier, VT_VOLUME, 8) &&
           VerifyField<double>(verifier, VT_VOLUME_LEFT, 8) &&
           verifier.EndTable();
  }
};

struct OrderBuilder {
  typedef Order Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_order_id(uint64_t order_id) {
    fbb_.AddElement<uint64_t>(Order::VT_ORDER_ID, order_id, 0);
  }
  void add_restore_time(int64_t restore_time) {
    fbb_.AddElement<int64_t>(Order::VT_RESTORE_TIME, restore_time, 0);
  }
  void add_status(kungfu::longfist::fb::OrderStatus status) {
    fbb_.AddElement<int8_t>(Order::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_instrument_id(::flatbuffers::Offset<::flatbuffers::String> instrument_id) {
    fbb_.AddOffset(Order::VT_INSTRUMENT_ID, instrument_id);
  }
  void add_limit_price(double limit_price) {
    fbb_.AddElement<double>(Order::VT_LIMIT_PRICE, limit_price, 0.0);
  }
  void add_volume(double volume) {
    fbb_.AddElement<double>(Order::VT_VOLUME, volume, 0.0);
  }
  void add_volume_left(double volume_left) {
    fbb_.AddElement<double>(Order::VT_VOLUME_LEFT, volume_left, 0.0);
  }
  explicit OrderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Order> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Order>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Order> CreateOrder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t order_id = 0,
    int64_t restore_time = 0,
    kungfu::longfist::fb::OrderStatus status = kungfu::longfist::fb::OrderStatus::Unknown,
    ::flatbuffers::Offset<::flatbuffers::String> instrument_id = 0,
    double limit_price = 0.0,
    double volume = 0.0,
    double volume_left = 0.0) {
  OrderBuilder builder_(_fbb);
  builder_.add_volume_left(volume_left);
  builder_.add_volume(volume);
  builder_.add_limit_price(limit_price);
  builder_.add_restore_time(restore_time);
  builder_.add_order_id(order_id);
  builder_.add_instrument_id(instrument_id);
  builder_.add_status(status);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Order> CreateOrderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t order_id = 0,
    int64_t restore_time = 0,
    kungfu::longfist::fb::OrderStatus status = kungfu::longfist::fb::OrderStatus::Unknown,
    const char *instrument_id = nullptr,
    double limit_price = 0.0,
    double volume = 0.0,
    double volume_left = 0.0) {
  auto instrument_id__ = instrument_id ? _fbb.CreateString(instrument_id) : 0;
  return kungfu::longfist::fb::CreateOrder(
      _fbb,
      order_id,
      restore_time,
      status,
      instrument_id__,
      limit_price,
      volume,
      volume_left);
}

inline const kungfu::longfist::fb::Order *GetOrder(const void *buf) {
  return ::flatbuffers::GetRoot<kungfu::longfist::fb::Order>(buf);
}

inline const kungfu::longfist::fb::Order *GetSizePrefixedOrder(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<kungfu::longfist::fb::Order>(buf);
}

inline Order *GetMutableOrder(void *buf) {
  return ::flatbuffers::GetMutableRoot<Order>(buf);
}

inline kungfu::longfist::fb::Order *GetMutableSizePrefixedOrder(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<kungfu::longfist::fb::Order>(buf);
}

inline bool VerifyOrderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<kungfu::longfist::fb::Order>(nullptr);
}

inline bool VerifySizePrefixedOrderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<kungfu::longfist::fb::Order>(nullptr);
}

inline void FinishOrderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::longfist::fb::Order> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOrderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::longfist::fb::Order> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fb
}  // namespace longfist
}  // namespace kungfu

#endif  // FLATBUFFERS_GENERATED_ORDER_KUNGFU_LONGFIST_FB_H_
