// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_ORDER_KUNGFU_LONGFIST_FB_H_
#define FLATBUFFERS_GENERATED_ORDER_KUNGFU_LONGFIST_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

namespace kungfu {
namespace longfist {
namespace fb {

struct Order;
struct OrderBuilder;

enum class OrderStatus : int8_t {
  Unknown = 0,
  Submitted = 1,
  Pending = 2,
  Cancelled = 3,
  Error = 4,
  Filled = 5,
  PartialFilledNotActive = 6,
  PartialFilledActive = 7,
  Lost = 8,
  Cancelling = 9,
  Pause = 10,
  PendingSettlement = 11,
  MIN = Unknown,
  MAX = PendingSettlement
};

inline const OrderStatus (&EnumValuesOrderStatus())[12] {
  static const OrderStatus values[] = {
    OrderStatus::Unknown,
    OrderStatus::Submitted,
    OrderStatus::Pending,
    OrderStatus::Cancelled,
    OrderStatus::Error,
    OrderStatus::Filled,
    OrderStatus::PartialFilledNotActive,
    OrderStatus::PartialFilledActive,
    OrderStatus::Lost,
    OrderStatus::Cancelling,
    OrderStatus::Pause,
    OrderStatus::PendingSettlement
  };
  return values;
}

inline const char * const *EnumNamesOrderStatus() {
  static const char * const names[13] = {
    "Unknown",
    "Submitted",
    "Pending",
    "Cancelled",
    "Error",
    "Filled",
    "PartialFilledNotActive",
    "PartialFilledActive",
    "Lost",
    "Cancelling",
    "Pause",
    "PendingSettlement",
    nullptr
  };
  return names;
}

inline const char *EnumNameOrderStatus(OrderStatus e) {
  if (::flatbuffers::IsOutRange(e, OrderStatus::Unknown, OrderStatus::PendingSettlement)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOrderStatus()[index];
}

enum class InstrumentType : int8_t {
  Unknown = 0,
  Stock = 1,
  StockOption = 2,
  TechStock = 3,
  Future = 4,
  Bond = 5,
  Fund = 6,
  Index = 7,
  Repo = 8,
  Crypto = 9,
  CryptoFuture = 10,
  CryptoUFuture = 11,
  MIN = Unknown,
  MAX = CryptoUFuture
};

inline const InstrumentType (&EnumValuesInstrumentType())[12] {
  static const InstrumentType values[] = {
    InstrumentType::Unknown,
    InstrumentType::Stock,
    InstrumentType::StockOption,
    InstrumentType::TechStock,
    InstrumentType::Future,
    InstrumentType::Bond,
    InstrumentType::Fund,
    InstrumentType::Index,
    InstrumentType::Repo,
    InstrumentType::Crypto,
    InstrumentType::CryptoFuture,
    InstrumentType::CryptoUFuture
  };
  return values;
}

inline const char * const *EnumNamesInstrumentType() {
  static const char * const names[13] = {
    "Unknown",
    "Stock",
    "StockOption",
    "TechStock",
    "Future",
    "Bond",
    "Fund",
    "Index",
    "Repo",
    "Crypto",
    "CryptoFuture",
    "CryptoUFuture",
    nullptr
  };
  return names;
}

inline const char *EnumNameInstrumentType(InstrumentType e) {
  if (::flatbuffers::IsOutRange(e, InstrumentType::Unknown, InstrumentType::CryptoUFuture)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesInstrumentType()[index];
}

enum class Side : int8_t {
  Buy = 0,
  Sell = 1,
  Lock = 2,
  Unlock = 3,
  Exec = 4,
  Drop = 5,
  Purchase = 6,
  Redemption = 7,
  Split = 8,
  Merge = 9,
  MarginTrade = 10,
  ShortSell = 11,
  RepayMargin = 12,
  RepayStock = 13,
  CashRepayMargin = 14,
  StockRepayStock = 15,
  SurplusStockTransfer = 16,
  GuaranteeStockTransferIn = 17,
  GuaranteeStockTransferOut = 18,
  GuaranteeStockBuy = 19,
  GuaranteeStockSell = 20,
  Unknown = 99,
  MIN = Buy,
  MAX = Unknown
};

inline const Side (&EnumValuesSide())[22] {
  static const Side values[] = {
    Side::Buy,
    Side::Sell,
    Side::Lock,
    Side::Unlock,
    Side::Exec,
    Side::Drop,
    Side::Purchase,
    Side::Redemption,
    Side::Split,
    Side::Merge,
    Side::MarginTrade,
    Side::ShortSell,
    Side::RepayMargin,
    Side::RepayStock,
    Side::CashRepayMargin,
    Side::StockRepayStock,
    Side::SurplusStockTransfer,
    Side::GuaranteeStockTransferIn,
    Side::GuaranteeStockTransferOut,
    Side::GuaranteeStockBuy,
    Side::GuaranteeStockSell,
    Side::Unknown
  };
  return values;
}

inline const char * const *EnumNamesSide() {
  static const char * const names[101] = {
    "Buy",
    "Sell",
    "Lock",
    "Unlock",
    "Exec",
    "Drop",
    "Purchase",
    "Redemption",
    "Split",
    "Merge",
    "MarginTrade",
    "ShortSell",
    "RepayMargin",
    "RepayStock",
    "CashRepayMargin",
    "StockRepayStock",
    "SurplusStockTransfer",
    "GuaranteeStockTransferIn",
    "GuaranteeStockTransferOut",
    "GuaranteeStockBuy",
    "GuaranteeStockSell",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNameSide(Side e) {
  if (::flatbuffers::IsOutRange(e, Side::Buy, Side::Unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesSide()[index];
}

enum class Offset : int8_t {
  Open = 0,
  Close = 1,
  CloseToday = 2,
  CloseYesterday = 3,
  MIN = Open,
  MAX = CloseYesterday
};

inline const Offset (&EnumValuesOffset())[4] {
  static const Offset values[] = {
    Offset::Open,
    Offset::Close,
    Offset::CloseToday,
    Offset::CloseYesterday
  };
  return values;
}

inline const char * const *EnumNamesOffset() {
  static const char * const names[5] = {
    "Open",
    "Close",
    "CloseToday",
    "CloseYesterday",
    nullptr
  };
  return names;
}

inline const char *EnumNameOffset(Offset e) {
  if (::flatbuffers::IsOutRange(e, Offset::Open, Offset::CloseYesterday)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesOffset()[index];
}

enum class HedgeFlag : int8_t {
  Speculation = 0,
  Arbitrage = 1,
  Hedge = 2,
  Covered = 3,
  MIN = Speculation,
  MAX = Covered
};

inline const HedgeFlag (&EnumValuesHedgeFlag())[4] {
  static const HedgeFlag values[] = {
    HedgeFlag::Speculation,
    HedgeFlag::Arbitrage,
    HedgeFlag::Hedge,
    HedgeFlag::Covered
  };
  return values;
}

inline const char * const *EnumNamesHedgeFlag() {
  static const char * const names[5] = {
    "Speculation",
    "Arbitrage",
    "Hedge",
    "Covered",
    nullptr
  };
  return names;
}

inline const char *EnumNameHedgeFlag(HedgeFlag e) {
  if (::flatbuffers::IsOutRange(e, HedgeFlag::Speculation, HedgeFlag::Covered)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesHedgeFlag()[index];
}

enum class PriceType : int8_t {
  Limit = 0,
  Any = 1,
  FakBest5 = 2,
  ForwardBest = 3,
  ReverseBest = 4,
  Fak = 5,
  Fok = 6,
  EnhancedLimit = 7,
  AtAuctionLimit = 8,
  AtAuction = 9,
  Unknown = 10,
  MIN = Limit,
  MAX = Unknown
};

inline const PriceType (&EnumValuesPriceType())[11] {
  static const PriceType values[] = {
    PriceType::Limit,
    PriceType::Any,
    PriceType::FakBest5,
    PriceType::ForwardBest,
    PriceType::ReverseBest,
    PriceType::Fak,
    PriceType::Fok,
    PriceType::EnhancedLimit,
    PriceType::AtAuctionLimit,
    PriceType::AtAuction,
    PriceType::Unknown
  };
  return values;
}

inline const char * const *EnumNamesPriceType() {
  static const char * const names[12] = {
    "Limit",
    "Any",
    "FakBest5",
    "ForwardBest",
    "ReverseBest",
    "Fak",
    "Fok",
    "EnhancedLimit",
    "AtAuctionLimit",
    "AtAuction",
    "Unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNamePriceType(PriceType e) {
  if (::flatbuffers::IsOutRange(e, PriceType::Limit, PriceType::Unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesPriceType()[index];
}

enum class VolumeCondition : int8_t {
  Any = 0,
  Min = 1,
  All = 2,
  MIN = Any,
  MAX = All
};

inline const VolumeCondition (&EnumValuesVolumeCondition())[3] {
  static const VolumeCondition values[] = {
    VolumeCondition::Any,
    VolumeCondition::Min,
    VolumeCondition::All
  };
  return values;
}

inline const char * const *EnumNamesVolumeCondition() {
  static const char * const names[4] = {
    "Any",
    "Min",
    "All",
    nullptr
  };
  return names;
}

inline const char *EnumNameVolumeCondition(VolumeCondition e) {
  if (::flatbuffers::IsOutRange(e, VolumeCondition::Any, VolumeCondition::All)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesVolumeCondition()[index];
}

enum class TimeCondition : int8_t {
  IOC = 0,
  GFD = 1,
  GTC = 2,
  GFS = 3,
  GTD = 4,
  GFA = 5,
  Unknown = 6,
  MIN = IOC,
  MAX = Unknown
};

inline const TimeCondition (&EnumValuesTimeCondition())[7] {
  static const TimeCondition values[] = {
    TimeCondition::IOC,
    TimeCondition::GFD,
    TimeCondition::GTC,
    TimeCondition::GFS,
    TimeCondition::GTD,
    TimeCondition::GFA,
    TimeCondition::Unknown
  };
  return values;
}

inline const char * const *EnumNamesTimeCondition() {
  static const char * const names[8] = {
    "IOC",
    "GFD",
    "GTC",
    "GFS",
    "GTD",
    "GFA",
    "Unknown",
    nullptr
  };
  return names;
}

inline const char *EnumNameTimeCondition(TimeCondition e) {
  if (::flatbuffers::IsOutRange(e, TimeCondition::IOC, TimeCondition::Unknown)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesTimeCondition()[index];
}

struct Order FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OrderBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ORDER_ID = 4,
    VT_EXTERNAL_ORDER_ID = 6,
    VT_PARENT_ID = 8,
    VT_INSERT_TIME = 10,
    VT_UPDATE_TIME = 12,
    VT_RESTORE_TIME = 14,
    VT_TRADING_DAY = 16,
    VT_INSTRUMENT_ID = 18,
    VT_EXCHANGE_ID = 20,
    VT_CONTRACT_ID = 22,
    VT_INSTRUMENT_TYPE = 24,
    VT_LIMIT_PRICE = 26,
    VT_FROZEN_PRICE = 28,
    VT_VOLUME = 30,
    VT_VOLUME_LEFT = 32,
    VT_TAX = 34,
    VT_COMMISSION = 36,
    VT_STATUS = 38,
    VT_ERROR_ID = 40,
    VT_ERROR_MSG = 42,
    VT_IS_SWAP = 44,
    VT_SIDE = 46,
    VT_OFFSET = 48,
    VT_HEDGE_FLAG = 50,
    VT_PRICE_TYPE = 52,
    VT_VOLUME_CONDITION = 54,
    VT_TIME_CONDITION = 56
  };
  uint64_t order_id() const {
    return GetField<uint64_t>(VT_ORDER_ID, 0);
  }
  bool mutate_order_id(uint64_t _order_id = 0) {
    return SetField<uint64_t>(VT_ORDER_ID, _order_id, 0);
  }
  const ::flatbuffers::String *external_order_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXTERNAL_ORDER_ID);
  }
  ::flatbuffers::String *mutable_external_order_id() {
    return GetPointer<::flatbuffers::String *>(VT_EXTERNAL_ORDER_ID);
  }
  uint64_t parent_id() const {
    return GetField<uint64_t>(VT_PARENT_ID, 0);
  }
  bool mutate_parent_id(uint64_t _parent_id = 0) {
    return SetField<uint64_t>(VT_PARENT_ID, _parent_id, 0);
  }
  int64_t insert_time() const {
    return GetField<int64_t>(VT_INSERT_TIME, 0);
  }
  bool mutate_insert_time(int64_t _insert_time = 0) {
    return SetField<int64_t>(VT_INSERT_TIME, _insert_time, 0);
  }
  int64_t update_time() const {
    return GetField<int64_t>(VT_UPDATE_TIME, 0);
  }
  bool mutate_update_time(int64_t _update_time = 0) {
    return SetField<int64_t>(VT_UPDATE_TIME, _update_time, 0);
  }
  int64_t restore_time() const {
    return GetField<int64_t>(VT_RESTORE_TIME, 0);
  }
  bool mutate_restore_time(int64_t _restore_time = 0) {
    return SetField<int64_t>(VT_RESTORE_TIME, _restore_time, 0);
  }
  const ::flatbuffers::String *trading_day() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRADING_DAY);
  }
  ::flatbuffers::String *mutable_trading_day() {
    return GetPointer<::flatbuffers::String *>(VT_TRADING_DAY);
  }
  const ::flatbuffers::String *instrument_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INSTRUMENT_ID);
  }
  ::flatbuffers::String *mutable_instrument_id() {
    return GetPointer<::flatbuffers::String *>(VT_INSTRUMENT_ID);
  }
  const ::flatbuffers::String *exchange_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXCHANGE_ID);
  }
  ::flatbuffers::String *mutable_exchange_id() {
    return GetPointer<::flatbuffers::String *>(VT_EXCHANGE_ID);
  }
  const ::flatbuffers::String *contract_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTRACT_ID);
  }
  ::flatbuffers::String *mutable_contract_id() {
    return GetPointer<::flatbuffers::String *>(VT_CONTRACT_ID);
  }
  kungfu::longfist::fb::InstrumentType instrument_type() const {
    return static_cast<kungfu::longfist::fb::InstrumentType>(GetField<int8_t>(VT_INSTRUMENT_TYPE, 0));
  }
  bool mutate_instrument_type(kungfu::longfist::fb::InstrumentType _instrument_type = static_cast<kungfu::longfist::fb::InstrumentType>(0)) {
    return SetField<int8_t>(VT_INSTRUMENT_TYPE, static_cast<int8_t>(_instrument_type), 0);
  }
  double limit_price() const {
    return GetField<double>(VT_LIMIT_PRICE, 0.0);
  }
  bool mutate_limit_price(double _limit_price = 0.0) {
    return SetField<double>(VT_LIMIT_PRICE, _limit_price, 0.0);
  }
  double frozen_price() const {
    return GetField<double>(VT_FROZEN_PRICE, 0.0);
  }
  bool mutate_frozen_price(double _frozen_price = 0.0) {
    return SetField<double>(VT_FROZEN_PRICE, _frozen_price, 0.0);
  }
  double volume() const {
    return GetField<double>(VT_VOLUME, 0.0);
  }
  bool mutate_volume(double _volume = 0.0) {
    return SetField<double>(VT_VOLUME, _volume, 0.0);
  }
  double volume_left() const {
    return GetField<double>(VT_VOLUME_LEFT, 0.0);
  }
  bool mutate_volume_left(double _volume_left = 0.0) {
    return SetField<double>(VT_VOLUME_LEFT, _volume_left, 0.0);
  }
  double tax() const {
    return GetField<double>(VT_TAX, 0.0);
  }
  bool mutate_tax(double _tax = 0.0) {
    return SetField<double>(VT_TAX, _tax, 0.0);
  }
  double commission() const {
    return GetField<double>(VT_COMMISSION, 0.0);
  }
  bool mutate_commission(double _commission = 0.0) {
    return SetField<double>(VT_COMMISSION, _commission, 0.0);
  }
  kungfu::longfist::fb::OrderStatus status() const {
    return static_cast<kungfu::longfist::fb::OrderStatus>(GetField<int8_t>(VT_STATUS, 0));
  }
  bool mutate_status(kungfu::longfist::fb::OrderStatus _status = static_cast<kungfu::longfist::fb::OrderStatus>(0)) {
    return SetField<int8_t>(VT_STATUS, static_cast<int8_t>(_status), 0);
  }
  int32_t error_id() const {
    return GetField<int32_t>(VT_ERROR_ID, 0);
  }
  bool mutate_error_id(int32_t _error_id = 0) {
    return SetField<int32_t>(VT_ERROR_ID, _error_id, 0);
  }
  const ::flatbuffers::String *error_msg() const {
    return GetPointer<const ::flatbuffers::String *>(VT_ERROR_MSG);
  }
  ::flatbuffers::String *mutable_error_msg() {
    return GetPointer<::flatbuffers::String *>(VT_ERROR_MSG);
  }
  bool is_swap() const {
    return GetField<uint8_t>(VT_IS_SWAP, 0) != 0;
  }
  bool mutate_is_swap(bool _is_swap = 0) {
    return SetField<uint8_t>(VT_IS_SWAP, static_cast<uint8_t>(_is_swap), 0);
  }
  kungfu::longfist::fb::Side side() const {
    return static_cast<kungfu::longfist::fb::Side>(GetField<int8_t>(VT_SIDE, 0));
  }
  bool mutate_side(kungfu::longfist::fb::Side _side = static_cast<kungfu::longfist::fb::Side>(0)) {
    return SetField<int8_t>(VT_SIDE, static_cast<int8_t>(_side), 0);
  }
  kungfu::longfist::fb::Offset offset() const {
    return static_cast<kungfu::longfist::fb::Offset>(GetField<int8_t>(VT_OFFSET, 0));
  }
  bool mutate_offset(kungfu::longfist::fb::Offset _offset = static_cast<kungfu::longfist::fb::Offset>(0)) {
    return SetField<int8_t>(VT_OFFSET, static_cast<int8_t>(_offset), 0);
  }
  kungfu::longfist::fb::HedgeFlag hedge_flag() const {
    return static_cast<kungfu::longfist::fb::HedgeFlag>(GetField<int8_t>(VT_HEDGE_FLAG, 0));
  }
  bool mutate_hedge_flag(kungfu::longfist::fb::HedgeFlag _hedge_flag = static_cast<kungfu::longfist::fb::HedgeFlag>(0)) {
    return SetField<int8_t>(VT_HEDGE_FLAG, static_cast<int8_t>(_hedge_flag), 0);
  }
  kungfu::longfist::fb::PriceType price_type() const {
    return static_cast<kungfu::longfist::fb::PriceType>(GetField<int8_t>(VT_PRICE_TYPE, 0));
  }
  bool mutate_price_type(kungfu::longfist::fb::PriceType _price_type = static_cast<kungfu::longfist::fb::PriceType>(0)) {
    return SetField<int8_t>(VT_PRICE_TYPE, static_cast<int8_t>(_price_type), 0);
  }
  kungfu::longfist::fb::VolumeCondition volume_condition() const {
    return static_cast<kungfu::longfist::fb::VolumeCondition>(GetField<int8_t>(VT_VOLUME_CONDITION, 0));
  }
  bool mutate_volume_condition(kungfu::longfist::fb::VolumeCondition _volume_condition = static_cast<kungfu::longfist::fb::VolumeCondition>(0)) {
    return SetField<int8_t>(VT_VOLUME_CONDITION, static_cast<int8_t>(_volume_condition), 0);
  }
  kungfu::longfist::fb::TimeCondition time_condition() const {
    return static_cast<kungfu::longfist::fb::TimeCondition>(GetField<int8_t>(VT_TIME_CONDITION, 0));
  }
  bool mutate_time_condition(kungfu::longfist::fb::TimeCondition _time_condition = static_cast<kungfu::longfist::fb::TimeCondition>(0)) {
    return SetField<int8_t>(VT_TIME_CONDITION, static_cast<int8_t>(_time_condition), 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_ORDER_ID, 8) &&
           VerifyOffset(verifier, VT_EXTERNAL_ORDER_ID) &&
           verifier.VerifyString(external_order_id()) &&
           VerifyField<uint64_t>(verifier, VT_PARENT_ID, 8) &&
           VerifyField<int64_t>(verifier, VT_INSERT_TIME, 8) &&
           VerifyField<int64_t>(verifier, VT_UPDATE_TIME, 8) &&
           VerifyField<int64_t>(verifier, VT_RESTORE_TIME, 8) &&
           VerifyOffset(verifier, VT_TRADING_DAY) &&
           verifier.VerifyString(trading_day()) &&
           VerifyOffset(verifier, VT_INSTRUMENT_ID) &&
           verifier.VerifyString(instrument_id()) &&
           VerifyOffset(verifier, VT_EXCHANGE_ID) &&
           verifier.VerifyString(exchange_id()) &&
           VerifyOffset(verifier, VT_CONTRACT_ID) &&
           verifier.VerifyString(contract_id()) &&
           VerifyField<int8_t>(verifier, VT_INSTRUMENT_TYPE, 1) &&
           VerifyField<double>(verifier, VT_LIMIT_PRICE, 8) &&
           VerifyField<double>(verifier, VT_FROZEN_PRICE, 8) &&
           VerifyField<double>(verifier, VT_VOLUME, 8) &&
           VerifyField<double>(verifier, VT_VOLUME_LEFT, 8) &&
           VerifyField<double>(verifier, VT_TAX, 8) &&
           VerifyField<double>(verifier, VT_COMMISSION, 8) &&
           VerifyField<int8_t>(verifier, VT_STATUS, 1) &&
           VerifyField<int32_t>(verifier, VT_ERROR_ID, 4) &&
           VerifyOffset(verifier, VT_ERROR_MSG) &&
           verifier.VerifyString(error_msg()) &&
           VerifyField<uint8_t>(verifier, VT_IS_SWAP, 1) &&
           VerifyField<int8_t>(verifier, VT_SIDE, 1) &&
           VerifyField<int8_t>(verifier, VT_OFFSET, 1) &&
           VerifyField<int8_t>(verifier, VT_HEDGE_FLAG, 1) &&
           VerifyField<int8_t>(verifier, VT_PRICE_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_VOLUME_CONDITION, 1) &&
           VerifyField<int8_t>(verifier, VT_TIME_CONDITION, 1) &&
           verifier.EndTable();
  }
};

struct OrderBuilder {
  typedef Order Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_order_id(uint64_t order_id) {
    fbb_.AddElement<uint64_t>(Order::VT_ORDER_ID, order_id, 0);
  }
  void add_external_order_id(::flatbuffers::Offset<::flatbuffers::String> external_order_id) {
    fbb_.AddOffset(Order::VT_EXTERNAL_ORDER_ID, external_order_id);
  }
  void add_parent_id(uint64_t parent_id) {
    fbb_.AddElement<uint64_t>(Order::VT_PARENT_ID, parent_id, 0);
  }
  void add_insert_time(int64_t insert_time) {
    fbb_.AddElement<int64_t>(Order::VT_INSERT_TIME, insert_time, 0);
  }
  void add_update_time(int64_t update_time) {
    fbb_.AddElement<int64_t>(Order::VT_UPDATE_TIME, update_time, 0);
  }
  void add_restore_time(int64_t restore_time) {
    fbb_.AddElement<int64_t>(Order::VT_RESTORE_TIME, restore_time, 0);
  }
  void add_trading_day(::flatbuffers::Offset<::flatbuffers::String> trading_day) {
    fbb_.AddOffset(Order::VT_TRADING_DAY, trading_day);
  }
  void add_instrument_id(::flatbuffers::Offset<::flatbuffers::String> instrument_id) {
    fbb_.AddOffset(Order::VT_INSTRUMENT_ID, instrument_id);
  }
  void add_exchange_id(::flatbuffers::Offset<::flatbuffers::String> exchange_id) {
    fbb_.AddOffset(Order::VT_EXCHANGE_ID, exchange_id);
  }
  void add_contract_id(::flatbuffers::Offset<::flatbuffers::String> contract_id) {
    fbb_.AddOffset(Order::VT_CONTRACT_ID, contract_id);
  }
  void add_instrument_type(kungfu::longfist::fb::InstrumentType instrument_type) {
    fbb_.AddElement<int8_t>(Order::VT_INSTRUMENT_TYPE, static_cast<int8_t>(instrument_type), 0);
  }
  void add_limit_price(double limit_price) {
    fbb_.AddElement<double>(Order::VT_LIMIT_PRICE, limit_price, 0.0);
  }
  void add_frozen_price(double frozen_price) {
    fbb_.AddElement<double>(Order::VT_FROZEN_PRICE, frozen_price, 0.0);
  }
  void add_volume(double volume) {
    fbb_.AddElement<double>(Order::VT_VOLUME, volume, 0.0);
  }
  void add_volume_left(double volume_left) {
    fbb_.AddElement<double>(Order::VT_VOLUME_LEFT, volume_left, 0.0);
  }
  void add_tax(double tax) {
    fbb_.AddElement<double>(Order::VT_TAX, tax, 0.0);
  }
  void add_commission(double commission) {
    fbb_.AddElement<double>(Order::VT_COMMISSION, commission, 0.0);
  }
  void add_status(kungfu::longfist::fb::OrderStatus status) {
    fbb_.AddElement<int8_t>(Order::VT_STATUS, static_cast<int8_t>(status), 0);
  }
  void add_error_id(int32_t error_id) {
    fbb_.AddElement<int32_t>(Order::VT_ERROR_ID, error_id, 0);
  }
  void add_error_msg(::flatbuffers::Offset<::flatbuffers::String> error_msg) {
    fbb_.AddOffset(Order::VT_ERROR_MSG, error_msg);
  }
  void add_is_swap(bool is_swap) {
    fbb_.AddElement<uint8_t>(Order::VT_IS_SWAP, static_cast<uint8_t>(is_swap), 0);
  }
  void add_side(kungfu::longfist::fb::Side side) {
    fbb_.AddElement<int8_t>(Order::VT_SIDE, static_cast<int8_t>(side), 0);
  }
  void add_offset(kungfu::longfist::fb::Offset offset) {
    fbb_.AddElement<int8_t>(Order::VT_OFFSET, static_cast<int8_t>(offset), 0);
  }
  void add_hedge_flag(kungfu::longfist::fb::HedgeFlag hedge_flag) {
    fbb_.AddElement<int8_t>(Order::VT_HEDGE_FLAG, static_cast<int8_t>(hedge_flag), 0);
  }
  void add_price_type(kungfu::longfist::fb::PriceType price_type) {
    fbb_.AddElement<int8_t>(Order::VT_PRICE_TYPE, static_cast<int8_t>(price_type), 0);
  }
  void add_volume_condition(kungfu::longfist::fb::VolumeCondition volume_condition) {
    fbb_.AddElement<int8_t>(Order::VT_VOLUME_CONDITION, static_cast<int8_t>(volume_condition), 0);
  }
  void add_time_condition(kungfu::longfist::fb::TimeCondition time_condition) {
    fbb_.AddElement<int8_t>(Order::VT_TIME_CONDITION, static_cast<int8_t>(time_condition), 0);
  }
  explicit OrderBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Order> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Order>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Order> CreateOrder(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t order_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> external_order_id = 0,
    uint64_t parent_id = 0,
    int64_t insert_time = 0,
    int64_t update_time = 0,
    int64_t restore_time = 0,
    ::flatbuffers::Offset<::flatbuffers::String> trading_day = 0,
    ::flatbuffers::Offset<::flatbuffers::String> instrument_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> exchange_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> contract_id = 0,
    kungfu::longfist::fb::InstrumentType instrument_type = kungfu::longfist::fb::InstrumentType::Unknown,
    double limit_price = 0.0,
    double frozen_price = 0.0,
    double volume = 0.0,
    double volume_left = 0.0,
    double tax = 0.0,
    double commission = 0.0,
    kungfu::longfist::fb::OrderStatus status = kungfu::longfist::fb::OrderStatus::Unknown,
    int32_t error_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> error_msg = 0,
    bool is_swap = false,
    kungfu::longfist::fb::Side side = kungfu::longfist::fb::Side::Buy,
    kungfu::longfist::fb::Offset offset = kungfu::longfist::fb::Offset::Open,
    kungfu::longfist::fb::HedgeFlag hedge_flag = kungfu::longfist::fb::HedgeFlag::Speculation,
    kungfu::longfist::fb::PriceType price_type = kungfu::longfist::fb::PriceType::Limit,
    kungfu::longfist::fb::VolumeCondition volume_condition = kungfu::longfist::fb::VolumeCondition::Any,
    kungfu::longfist::fb::TimeCondition time_condition = kungfu::longfist::fb::TimeCondition::IOC) {
  OrderBuilder builder_(_fbb);
  builder_.add_commission(commission);
  builder_.add_tax(tax);
  builder_.add_volume_left(volume_left);
  builder_.add_volume(volume);
  builder_.add_frozen_price(frozen_price);
  builder_.add_limit_price(limit_price);
  builder_.add_restore_time(restore_time);
  builder_.add_update_time(update_time);
  builder_.add_insert_time(insert_time);
  builder_.add_parent_id(parent_id);
  builder_.add_order_id(order_id);
  builder_.add_error_msg(error_msg);
  builder_.add_error_id(error_id);
  builder_.add_contract_id(contract_id);
  builder_.add_exchange_id(exchange_id);
  builder_.add_instrument_id(instrument_id);
  builder_.add_trading_day(trading_day);
  builder_.add_external_order_id(external_order_id);
  builder_.add_time_condition(time_condition);
  builder_.add_volume_condition(volume_condition);
  builder_.add_price_type(price_type);
  builder_.add_hedge_flag(hedge_flag);
  builder_.add_offset(offset);
  builder_.add_side(side);
  builder_.add_is_swap(is_swap);
  builder_.add_status(status);
  builder_.add_instrument_type(instrument_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Order> CreateOrderDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t order_id = 0,
    const char *external_order_id = nullptr,
    uint64_t parent_id = 0,
    int64_t insert_time = 0,
    int64_t update_time = 0,
    int64_t restore_time = 0,
    const char *trading_day = nullptr,
    const char *instrument_id = nullptr,
    const char *exchange_id = nullptr,
    const char *contract_id = nullptr,
    kungfu::longfist::fb::InstrumentType instrument_type = kungfu::longfist::fb::InstrumentType::Unknown,
    double limit_price = 0.0,
    double frozen_price = 0.0,
    double volume = 0.0,
    double volume_left = 0.0,
    double tax = 0.0,
    double commission = 0.0,
    kungfu::longfist::fb::OrderStatus status = kungfu::longfist::fb::OrderStatus::Unknown,
    int32_t error_id = 0,
    const char *error_msg = nullptr,
    bool is_swap = false,
    kungfu::longfist::fb::Side side = kungfu::longfist::fb::Side::Buy,
    kungfu::longfist::fb::Offset offset = kungfu::longfist::fb::Offset::Open,
    kungfu::longfist::fb::HedgeFlag hedge_flag = kungfu::longfist::fb::HedgeFlag::Speculation,
    kungfu::longfist::fb::PriceType price_type = kungfu::longfist::fb::PriceType::Limit,
    kungfu::longfist::fb::VolumeCondition volume_condition = kungfu::longfist::fb::VolumeCondition::Any,
    kungfu::longfist::fb::TimeCondition time_condition = kungfu::longfist::fb::TimeCondition::IOC) {
  auto external_order_id__ = external_order_id ? _fbb.CreateString(external_order_id) : 0;
  auto trading_day__ = trading_day ? _fbb.CreateString(trading_day) : 0;
  auto instrument_id__ = instrument_id ? _fbb.CreateString(instrument_id) : 0;
  auto exchange_id__ = exchange_id ? _fbb.CreateString(exchange_id) : 0;
  auto contract_id__ = contract_id ? _fbb.CreateString(contract_id) : 0;
  auto error_msg__ = error_msg ? _fbb.CreateString(error_msg) : 0;
  return kungfu::longfist::fb::CreateOrder(
      _fbb,
      order_id,
      external_order_id__,
      parent_id,
      insert_time,
      update_time,
      restore_time,
      trading_day__,
      instrument_id__,
      exchange_id__,
      contract_id__,
      instrument_type,
      limit_price,
      frozen_price,
      volume,
      volume_left,
      tax,
      commission,
      status,
      error_id,
      error_msg__,
      is_swap,
      side,
      offset,
      hedge_flag,
      price_type,
      volume_condition,
      time_condition);
}

inline const kungfu::longfist::fb::Order *GetOrder(const void *buf) {
  return ::flatbuffers::GetRoot<kungfu::longfist::fb::Order>(buf);
}

inline const kungfu::longfist::fb::Order *GetSizePrefixedOrder(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<kungfu::longfist::fb::Order>(buf);
}

inline Order *GetMutableOrder(void *buf) {
  return ::flatbuffers::GetMutableRoot<Order>(buf);
}

inline kungfu::longfist::fb::Order *GetMutableSizePrefixedOrder(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<kungfu::longfist::fb::Order>(buf);
}

inline bool VerifyOrderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<kungfu::longfist::fb::Order>(nullptr);
}

inline bool VerifySizePrefixedOrderBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<kungfu::longfist::fb::Order>(nullptr);
}

inline void FinishOrderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::longfist::fb::Order> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedOrderBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::longfist::fb::Order> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fb
}  // namespace longfist
}  // namespace kungfu

#endif  // FLATBUFFERS_GENERATED_ORDER_KUNGFU_LONGFIST_FB_H_
