// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TRADE_KUNGFU_LONGFIST_FB_H_
#define FLATBUFFERS_GENERATED_TRADE_KUNGFU_LONGFIST_FB_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 9 &&
              FLATBUFFERS_VERSION_REVISION == 23,
             "Non-compatible flatbuffers version included");

#include "order_generated.h"

namespace kungfu {
namespace longfist {
namespace fb {

struct Trade;
struct TradeBuilder;

struct Trade FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TradeBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TRADE_ID = 4,
    VT_ORDER_ID = 6,
    VT_PARENT_ORDER_ID = 8,
    VT_EXTERNAL_ORDER_ID = 10,
    VT_EXTERNAL_TRADE_ID = 12,
    VT_TRADE_TIME = 14,
    VT_RESTORE_TIME = 16,
    VT_TRADING_DAY = 18,
    VT_INSTRUMENT_ID = 20,
    VT_EXCHANGE_ID = 22,
    VT_CONTRACT_ID = 24,
    VT_INSTRUMENT_TYPE = 26,
    VT_SIDE = 28,
    VT_OFFSET = 30,
    VT_HEDGE_FLAG = 32,
    VT_PRICE = 34,
    VT_VOLUME = 36,
    VT_TAX = 38,
    VT_COMMISSION = 40
  };
  uint64_t trade_id() const {
    return GetField<uint64_t>(VT_TRADE_ID, 0);
  }
  bool mutate_trade_id(uint64_t _trade_id = 0) {
    return SetField<uint64_t>(VT_TRADE_ID, _trade_id, 0);
  }
  uint64_t order_id() const {
    return GetField<uint64_t>(VT_ORDER_ID, 0);
  }
  bool mutate_order_id(uint64_t _order_id = 0) {
    return SetField<uint64_t>(VT_ORDER_ID, _order_id, 0);
  }
  uint64_t parent_order_id() const {
    return GetField<uint64_t>(VT_PARENT_ORDER_ID, 0);
  }
  bool mutate_parent_order_id(uint64_t _parent_order_id = 0) {
    return SetField<uint64_t>(VT_PARENT_ORDER_ID, _parent_order_id, 0);
  }
  const ::flatbuffers::String *external_order_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXTERNAL_ORDER_ID);
  }
  ::flatbuffers::String *mutable_external_order_id() {
    return GetPointer<::flatbuffers::String *>(VT_EXTERNAL_ORDER_ID);
  }
  const ::flatbuffers::String *external_trade_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXTERNAL_TRADE_ID);
  }
  ::flatbuffers::String *mutable_external_trade_id() {
    return GetPointer<::flatbuffers::String *>(VT_EXTERNAL_TRADE_ID);
  }
  int64_t trade_time() const {
    return GetField<int64_t>(VT_TRADE_TIME, 0);
  }
  bool mutate_trade_time(int64_t _trade_time = 0) {
    return SetField<int64_t>(VT_TRADE_TIME, _trade_time, 0);
  }
  int64_t restore_time() const {
    return GetField<int64_t>(VT_RESTORE_TIME, 0);
  }
  bool mutate_restore_time(int64_t _restore_time = 0) {
    return SetField<int64_t>(VT_RESTORE_TIME, _restore_time, 0);
  }
  const ::flatbuffers::String *trading_day() const {
    return GetPointer<const ::flatbuffers::String *>(VT_TRADING_DAY);
  }
  ::flatbuffers::String *mutable_trading_day() {
    return GetPointer<::flatbuffers::String *>(VT_TRADING_DAY);
  }
  const ::flatbuffers::String *instrument_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_INSTRUMENT_ID);
  }
  ::flatbuffers::String *mutable_instrument_id() {
    return GetPointer<::flatbuffers::String *>(VT_INSTRUMENT_ID);
  }
  const ::flatbuffers::String *exchange_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_EXCHANGE_ID);
  }
  ::flatbuffers::String *mutable_exchange_id() {
    return GetPointer<::flatbuffers::String *>(VT_EXCHANGE_ID);
  }
  const ::flatbuffers::String *contract_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_CONTRACT_ID);
  }
  ::flatbuffers::String *mutable_contract_id() {
    return GetPointer<::flatbuffers::String *>(VT_CONTRACT_ID);
  }
  kungfu::longfist::fb::InstrumentType instrument_type() const {
    return static_cast<kungfu::longfist::fb::InstrumentType>(GetField<int8_t>(VT_INSTRUMENT_TYPE, 0));
  }
  bool mutate_instrument_type(kungfu::longfist::fb::InstrumentType _instrument_type = static_cast<kungfu::longfist::fb::InstrumentType>(0)) {
    return SetField<int8_t>(VT_INSTRUMENT_TYPE, static_cast<int8_t>(_instrument_type), 0);
  }
  kungfu::longfist::fb::Side side() const {
    return static_cast<kungfu::longfist::fb::Side>(GetField<int8_t>(VT_SIDE, 0));
  }
  bool mutate_side(kungfu::longfist::fb::Side _side = static_cast<kungfu::longfist::fb::Side>(0)) {
    return SetField<int8_t>(VT_SIDE, static_cast<int8_t>(_side), 0);
  }
  kungfu::longfist::fb::Offset offset() const {
    return static_cast<kungfu::longfist::fb::Offset>(GetField<int8_t>(VT_OFFSET, 0));
  }
  bool mutate_offset(kungfu::longfist::fb::Offset _offset = static_cast<kungfu::longfist::fb::Offset>(0)) {
    return SetField<int8_t>(VT_OFFSET, static_cast<int8_t>(_offset), 0);
  }
  kungfu::longfist::fb::HedgeFlag hedge_flag() const {
    return static_cast<kungfu::longfist::fb::HedgeFlag>(GetField<int8_t>(VT_HEDGE_FLAG, 0));
  }
  bool mutate_hedge_flag(kungfu::longfist::fb::HedgeFlag _hedge_flag = static_cast<kungfu::longfist::fb::HedgeFlag>(0)) {
    return SetField<int8_t>(VT_HEDGE_FLAG, static_cast<int8_t>(_hedge_flag), 0);
  }
  double price() const {
    return GetField<double>(VT_PRICE, 0.0);
  }
  bool mutate_price(double _price = 0.0) {
    return SetField<double>(VT_PRICE, _price, 0.0);
  }
  double volume() const {
    return GetField<double>(VT_VOLUME, 0.0);
  }
  bool mutate_volume(double _volume = 0.0) {
    return SetField<double>(VT_VOLUME, _volume, 0.0);
  }
  double tax() const {
    return GetField<double>(VT_TAX, 0.0);
  }
  bool mutate_tax(double _tax = 0.0) {
    return SetField<double>(VT_TAX, _tax, 0.0);
  }
  double commission() const {
    return GetField<double>(VT_COMMISSION, 0.0);
  }
  bool mutate_commission(double _commission = 0.0) {
    return SetField<double>(VT_COMMISSION, _commission, 0.0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint64_t>(verifier, VT_TRADE_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_ORDER_ID, 8) &&
           VerifyField<uint64_t>(verifier, VT_PARENT_ORDER_ID, 8) &&
           VerifyOffset(verifier, VT_EXTERNAL_ORDER_ID) &&
           verifier.VerifyString(external_order_id()) &&
           VerifyOffset(verifier, VT_EXTERNAL_TRADE_ID) &&
           verifier.VerifyString(external_trade_id()) &&
           VerifyField<int64_t>(verifier, VT_TRADE_TIME, 8) &&
           VerifyField<int64_t>(verifier, VT_RESTORE_TIME, 8) &&
           VerifyOffset(verifier, VT_TRADING_DAY) &&
           verifier.VerifyString(trading_day()) &&
           VerifyOffset(verifier, VT_INSTRUMENT_ID) &&
           verifier.VerifyString(instrument_id()) &&
           VerifyOffset(verifier, VT_EXCHANGE_ID) &&
           verifier.VerifyString(exchange_id()) &&
           VerifyOffset(verifier, VT_CONTRACT_ID) &&
           verifier.VerifyString(contract_id()) &&
           VerifyField<int8_t>(verifier, VT_INSTRUMENT_TYPE, 1) &&
           VerifyField<int8_t>(verifier, VT_SIDE, 1) &&
           VerifyField<int8_t>(verifier, VT_OFFSET, 1) &&
           VerifyField<int8_t>(verifier, VT_HEDGE_FLAG, 1) &&
           VerifyField<double>(verifier, VT_PRICE, 8) &&
           VerifyField<double>(verifier, VT_VOLUME, 8) &&
           VerifyField<double>(verifier, VT_TAX, 8) &&
           VerifyField<double>(verifier, VT_COMMISSION, 8) &&
           verifier.EndTable();
  }
};

struct TradeBuilder {
  typedef Trade Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_trade_id(uint64_t trade_id) {
    fbb_.AddElement<uint64_t>(Trade::VT_TRADE_ID, trade_id, 0);
  }
  void add_order_id(uint64_t order_id) {
    fbb_.AddElement<uint64_t>(Trade::VT_ORDER_ID, order_id, 0);
  }
  void add_parent_order_id(uint64_t parent_order_id) {
    fbb_.AddElement<uint64_t>(Trade::VT_PARENT_ORDER_ID, parent_order_id, 0);
  }
  void add_external_order_id(::flatbuffers::Offset<::flatbuffers::String> external_order_id) {
    fbb_.AddOffset(Trade::VT_EXTERNAL_ORDER_ID, external_order_id);
  }
  void add_external_trade_id(::flatbuffers::Offset<::flatbuffers::String> external_trade_id) {
    fbb_.AddOffset(Trade::VT_EXTERNAL_TRADE_ID, external_trade_id);
  }
  void add_trade_time(int64_t trade_time) {
    fbb_.AddElement<int64_t>(Trade::VT_TRADE_TIME, trade_time, 0);
  }
  void add_restore_time(int64_t restore_time) {
    fbb_.AddElement<int64_t>(Trade::VT_RESTORE_TIME, restore_time, 0);
  }
  void add_trading_day(::flatbuffers::Offset<::flatbuffers::String> trading_day) {
    fbb_.AddOffset(Trade::VT_TRADING_DAY, trading_day);
  }
  void add_instrument_id(::flatbuffers::Offset<::flatbuffers::String> instrument_id) {
    fbb_.AddOffset(Trade::VT_INSTRUMENT_ID, instrument_id);
  }
  void add_exchange_id(::flatbuffers::Offset<::flatbuffers::String> exchange_id) {
    fbb_.AddOffset(Trade::VT_EXCHANGE_ID, exchange_id);
  }
  void add_contract_id(::flatbuffers::Offset<::flatbuffers::String> contract_id) {
    fbb_.AddOffset(Trade::VT_CONTRACT_ID, contract_id);
  }
  void add_instrument_type(kungfu::longfist::fb::InstrumentType instrument_type) {
    fbb_.AddElement<int8_t>(Trade::VT_INSTRUMENT_TYPE, static_cast<int8_t>(instrument_type), 0);
  }
  void add_side(kungfu::longfist::fb::Side side) {
    fbb_.AddElement<int8_t>(Trade::VT_SIDE, static_cast<int8_t>(side), 0);
  }
  void add_offset(kungfu::longfist::fb::Offset offset) {
    fbb_.AddElement<int8_t>(Trade::VT_OFFSET, static_cast<int8_t>(offset), 0);
  }
  void add_hedge_flag(kungfu::longfist::fb::HedgeFlag hedge_flag) {
    fbb_.AddElement<int8_t>(Trade::VT_HEDGE_FLAG, static_cast<int8_t>(hedge_flag), 0);
  }
  void add_price(double price) {
    fbb_.AddElement<double>(Trade::VT_PRICE, price, 0.0);
  }
  void add_volume(double volume) {
    fbb_.AddElement<double>(Trade::VT_VOLUME, volume, 0.0);
  }
  void add_tax(double tax) {
    fbb_.AddElement<double>(Trade::VT_TAX, tax, 0.0);
  }
  void add_commission(double commission) {
    fbb_.AddElement<double>(Trade::VT_COMMISSION, commission, 0.0);
  }
  explicit TradeBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<Trade> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<Trade>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<Trade> CreateTrade(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t trade_id = 0,
    uint64_t order_id = 0,
    uint64_t parent_order_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> external_order_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> external_trade_id = 0,
    int64_t trade_time = 0,
    int64_t restore_time = 0,
    ::flatbuffers::Offset<::flatbuffers::String> trading_day = 0,
    ::flatbuffers::Offset<::flatbuffers::String> instrument_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> exchange_id = 0,
    ::flatbuffers::Offset<::flatbuffers::String> contract_id = 0,
    kungfu::longfist::fb::InstrumentType instrument_type = kungfu::longfist::fb::InstrumentType::Unknown,
    kungfu::longfist::fb::Side side = kungfu::longfist::fb::Side::Buy,
    kungfu::longfist::fb::Offset offset = kungfu::longfist::fb::Offset::Open,
    kungfu::longfist::fb::HedgeFlag hedge_flag = kungfu::longfist::fb::HedgeFlag::Speculation,
    double price = 0.0,
    double volume = 0.0,
    double tax = 0.0,
    double commission = 0.0) {
  TradeBuilder builder_(_fbb);
  builder_.add_commission(commission);
  builder_.add_tax(tax);
  builder_.add_volume(volume);
  builder_.add_price(price);
  builder_.add_restore_time(restore_time);
  builder_.add_trade_time(trade_time);
  builder_.add_parent_order_id(parent_order_id);
  builder_.add_order_id(order_id);
  builder_.add_trade_id(trade_id);
  builder_.add_contract_id(contract_id);
  builder_.add_exchange_id(exchange_id);
  builder_.add_instrument_id(instrument_id);
  builder_.add_trading_day(trading_day);
  builder_.add_external_trade_id(external_trade_id);
  builder_.add_external_order_id(external_order_id);
  builder_.add_hedge_flag(hedge_flag);
  builder_.add_offset(offset);
  builder_.add_side(side);
  builder_.add_instrument_type(instrument_type);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<Trade> CreateTradeDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint64_t trade_id = 0,
    uint64_t order_id = 0,
    uint64_t parent_order_id = 0,
    const char *external_order_id = nullptr,
    const char *external_trade_id = nullptr,
    int64_t trade_time = 0,
    int64_t restore_time = 0,
    const char *trading_day = nullptr,
    const char *instrument_id = nullptr,
    const char *exchange_id = nullptr,
    const char *contract_id = nullptr,
    kungfu::longfist::fb::InstrumentType instrument_type = kungfu::longfist::fb::InstrumentType::Unknown,
    kungfu::longfist::fb::Side side = kungfu::longfist::fb::Side::Buy,
    kungfu::longfist::fb::Offset offset = kungfu::longfist::fb::Offset::Open,
    kungfu::longfist::fb::HedgeFlag hedge_flag = kungfu::longfist::fb::HedgeFlag::Speculation,
    double price = 0.0,
    double volume = 0.0,
    double tax = 0.0,
    double commission = 0.0) {
  auto external_order_id__ = external_order_id ? _fbb.CreateString(external_order_id) : 0;
  auto external_trade_id__ = external_trade_id ? _fbb.CreateString(external_trade_id) : 0;
  auto trading_day__ = trading_day ? _fbb.CreateString(trading_day) : 0;
  auto instrument_id__ = instrument_id ? _fbb.CreateString(instrument_id) : 0;
  auto exchange_id__ = exchange_id ? _fbb.CreateString(exchange_id) : 0;
  auto contract_id__ = contract_id ? _fbb.CreateString(contract_id) : 0;
  return kungfu::longfist::fb::CreateTrade(
      _fbb,
      trade_id,
      order_id,
      parent_order_id,
      external_order_id__,
      external_trade_id__,
      trade_time,
      restore_time,
      trading_day__,
      instrument_id__,
      exchange_id__,
      contract_id__,
      instrument_type,
      side,
      offset,
      hedge_flag,
      price,
      volume,
      tax,
      commission);
}

inline const kungfu::longfist::fb::Trade *GetTrade(const void *buf) {
  return ::flatbuffers::GetRoot<kungfu::longfist::fb::Trade>(buf);
}

inline const kungfu::longfist::fb::Trade *GetSizePrefixedTrade(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<kungfu::longfist::fb::Trade>(buf);
}

inline Trade *GetMutableTrade(void *buf) {
  return ::flatbuffers::GetMutableRoot<Trade>(buf);
}

inline kungfu::longfist::fb::Trade *GetMutableSizePrefixedTrade(void *buf) {
  return ::flatbuffers::GetMutableSizePrefixedRoot<kungfu::longfist::fb::Trade>(buf);
}

inline bool VerifyTradeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<kungfu::longfist::fb::Trade>(nullptr);
}

inline bool VerifySizePrefixedTradeBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<kungfu::longfist::fb::Trade>(nullptr);
}

inline void FinishTradeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::longfist::fb::Trade> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedTradeBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<kungfu::longfist::fb::Trade> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace fb
}  // namespace longfist
}  // namespace kungfu

#endif  // FLATBUFFERS_GENERATED_TRADE_KUNGFU_LONGFIST_FB_H_
